export const fakeCreators = [
  {
    username: "User Name",
    src: "/some-man.png",
    account: "068bku9878hgvkuvl7tyurd865v",
    isConfirmed: true,
    id: "1",
  },
  {
    username: "User Name",
    src: "/some-man.png",
    account: "068bku9878hgvkuvl7tyurd865v",
    isConfirmed: true,
    id: "2",
  },
  {
    username: "User Name",
    src: "/some-man.png",
    account: "068bku9878hgvkuvl7tyurd865v",
    isConfirmed: true,
    id: "3",
  },
  {
    username: "User Name",
    src: "/some-man.png",
    account: "068bku9878hgvkuvl7tyurd865v",
    isConfirmed: true,
    id: "4",
  },
  {
    username: "User Name",
    src: "/some-man.png",
    account: "068bku9878hgvkuvl7tyurd865v",
    isConfirmed: true,
    id: "5",
  },
  {
    username: "User Name",
    src: "/some-man.png",
    account: "068bku9878hgvkuvl7tyurd865v",
    isConfirmed: true,
    id: "6",
  },
  {
    username: "User Name",
    src: "/some-man.png",
    account: "068bku9878hgvkuvl7tyurd865v",
    isConfirmed: true,
    id: "7",
  },
  {
    username: "User Name",
    src: "/some-man.png",
    account: "068bku9878hgvkuvl7tyurd865v",
    isConfirmed: true,
    id: "8",
  },
  {
    username: "User Name",
    src: "/some-man.png",
    account: "068bku9878hgvkuvl7tyurd865v",
    isConfirmed: true,
    id: "9",
  },
  {
    username: "User Name",
    src: "/some-man.png",
    account: "068bku9878hgvkuvl7tyurd865v",
    isConfirmed: true,
    id: "10",
  },
];
