image:
  name: atlassian/default-image:3

pipelines:
  branches:   
    feature/adding-ci:
      - step:
          name: Build and publish docker image.
          services:
            - docker
          caches:
            - pip3
          script:
            - pip3 install awscli
            - aws configure set aws_access_key_id "${AWS_ACCESS_KEY_ID}"
            - aws configure set aws_secret_access_key "${AWS_SECRET_ACCESS_KEY}"
            - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin "${AWS_USERNAME}"
            - export IMAGE_NAME="${AWS_USERNAME}/${IMAGE_NAME}:latest"
            - docker build -t $IMAGE_NAME .
            - docker push $IMAGE_NAME
      - step:
          name: Deploy to ECS
          script:
            - pipe: atlassian/aws-ecs-deploy:1.6.2
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: 'us-east-1'
                CLUSTER_NAME: '${CLUSTER_ECS}'
                SERVICE_NAME: '${SERVICE_ECS}'
                FORCE_NEW_DEPLOYMENT: 'true'
definitions:
  services:
    docker:
      memory: 2048

