image:
  name: atlassian/default-image:3

pipelines:
  branches:   
    feature/adding-ci:
      - step:
          name: Build and publish docker image.
          services:
            - docker
          script:
            - export IMAGE_NAME="${DOCKERHUB_USERNAME}/${BITBUCKET_REPO_SLUG}:latest"
            - docker build -t "${IMAGE_NAME}" .
            - pipe: atlassian/aws-ecr-push-image:1.5.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                IMAGE_NAME: ${BITBUCKET_REPO_SLUG}
                ECR_PUBLIC: "false"
      - step:
          name: Deploy to ECS
          script:
            - pipe: atlassian/aws-ecs-deploy:1.6.2
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: 'us-east-1'
                CLUSTER_NAME: '${CLUSTER_ECS}'
                SERVICE_NAME: '${SERVICE_ECS}'
                FORCE_NEW_DEPLOYMENT: 'true'
definitions:
  services:
    docker:
      memory: 2048

