export const fakeNFTs = [
  {
    src: "/testImages/football.png",
    title: "Connor van den Berg 2020-21",
    price: 120.59,
    priceDifference: {
      direction: "down",
      percent: 15.3,
    },
    username: "UEFA",
    account: "uv7597gug865d",
    tag: "3d Art",
    rewards: "common",
    id: "1",
  },
  {
    src: "/testImages/hand.png",
    title: "Diamond Hand Black",
    price: 1017.05,
    priceDifference: {
      direction: "up",
      percent: 25.00,
    },
    username: "Diamond Hands Ltd.",
    account: "080ukhbiuyg87g09u0lklkn",
    tag: "3d Art",
    rewards: "common",
    id: "2",
  },
  {
    src: "/testImages/rock.png",
    title: "Greta Van Fleet @ Wings Event Center",
    price: 310.05,
    priceDifference: {
      direction: "down",
      percent: 15.3,
    },
    username: "Diamond Hands Ltd.",
    account: "uv7597gug865d",
    tag: "Art & Theater",
    rewards: "common",
    id: "3",
  },
  {
    src: "/testImages/football.png",
    title: "Connor van den Berg 2020-21",
    price: 310.05,
    priceDifference: {
      direction: "up",
      percent: 15.3,
    },
    username: "UEFA",
    account: "9yhviutf875foubpi",
    tag: "Art & Theater",
    rewards: "common",
    id: "4",
  },
  {
    src: "/testImages/hand.png",
    title: "Diamond Hand Black",
    price: 10000.01,
    priceDifference: {
      direction: "up",
      percent: 0.00,
    },
    username: "Diamond Hands Ltd.",
    account: "uv7597gug865d",
    tag: "Art & Theater",
    rewards: "common",
    id: "5",
  },
  {
    src: "/testImages/rock.png",
    title: "Greta Van Fleet @ Wings Event Center",
    price: 310.05,
    priceDifference: {
      direction: "up",
      percent: 15.3,
    },
    username: "Diamond Hands Ltd.",
    account: "uv7597gug865d",
    tag: "Art & Theater",
    rewards: "common",
    id: "6",
  },
  {
    src: "/testImages/football.png",
    title: "Greta Van Fleet @ Wings Event Center",
    price: 310.05,
    priceDifference: {
      direction: "up",
      percent: 15.3,
    },
    username: "Diamond Hands Ltd.",
    account: "uv7597gug865d",
    tag: "Art & Theater",
    rewards: "common",
    id: "7",
  },
  {
    src: "/testImages/hand.png",
    title: "Greta Van Fleet @ Wings Event Center",
    price: 310.05,
    priceDifference: {
      direction: "up",
      percent: 15.3,
    },
    username: "Diamond Hands Ltd.",
    account: "uv7597gug865d",
    tag: "Art & Theater",
    rewards: "common",
    id: "8",
  },
  {
    src: "/testImages/rock.png",
    title: "Greta Van Fleet @ Wings Event Center",
    price: 310.05,
    priceDifference: {
      direction: "up",
      percent: 15.3,
    },
    username: "Diamond Hands Ltd.",
    account: "uv7597gug865d",
    tag: "Art & Theater",
    rewards: "common",
    id: "9",
  },
  {
    src: "/testImages/football.png",
    title: "Greta Van Fleet @ Wings Event Center",
    price: 310.05,
    priceDifference: {
      direction: "up",
      percent: 15.3,
    },
    username: "Diamond Hands Ltd.",
    account: "uv7597gug865d",
    tag: "Art & Theater",
    rewards: "common",
    id: "10",
  },
  {
    src: "/testImages/hand.png",
    title: "Greta Van Fleet @ Wings Event Center",
    price: 310.05,
    priceDifference: {
      direction: "up",
      percent: 15.3,
    },
    username: "Diamond Hands Ltd.",
    account: "uv7597gug865d",
    tag: "Art & Theater",
    rewards: "common",
    id: "11",
  },
];
