import Head from "next/head";
import Image from "next/image";
import { Header } from "../layout/Header/Header";
import { HottestNFTCollectibles } from "../page-components/MainPage/HottestNFTCollectibles/HottestNFTCollectibles";
import { PopularNFTCard } from "../src/components/PopularNFTCard/PopularNFTCard";
import { Ribbon } from "../src/components/Ribbon/Ribbon";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
      </Head>
      <Header />
      <HottestNFTCollectibles />
    </div>
  );
}
