import Head from "next/head";
import { withLayout } from "../layout/Layout";
import { MainPage } from "../src/page-components/MainPage";

function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
      </Head>
      <MainPage />
    </>
  );
}

export default withLayout(Home);
